version: 2

artifacts:
  - name: planning
    build:
      type: custom
      runtime:
        type: standard1/arm64/large
      source:
        vcstool:
          repositories_files:
            - autoware.repos
          import_path: src
      base_container_image:
        from: ghcr.io/oguzkaganozt/autoware-openadk:ces-planning-after-aarch64
      phases:
        - name: init
          exec: "true"
      output_container_image:
        from: init
        workdir: /autoware
  - name: scenario_simulator_v2
    build:
      type: custom
      runtime:
        type: standard1/arm64/large
      source:
        vcstool:
          repositories_files:
            - dependency_humble.repos
          import_path: src
      base_container_image:
        from: ghcr.io/oguzkaganozt/autoware-openadk:ces-simulator-aarch64
      phases:
        - name: init
          exec: "true"
      output_container_image:
        from: init

simulations:
  - name: planning_sim
    type: planning_sim_v2
    simulator:
      deployment:
        type: container
        artifact: scenario_simulator_v2
      runtime:
        type: standard1/arm64/medium
      parameters:
        launch_autoware: "false"
        autoware_launch_package: autoware_launch
        autoware_launch_file: planning_simulator.launch.xml
        architecture_type: awf/universe
        vehicle_model: sample_vehicle
        sensor_model: sample_sensor_kit
        initialize_duration: "45"
    components:
      - name: planning
        deployment:
          type: container
          artifact: planning
        runtime:
          type: standard1/arm64/medium
        environment_variables:
          PATH: /autoware/install/trtexec_vendor/bin:/opt/ros/humble/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        application:
          roslaunch:
            package_name: autoware_launch
            file_name: planning_simulator.launch.xml
            arguments:
              sensor_model: sample_sensor_kit
              vehicle_model: sample_vehicle
              map_path: ${map_path}
              scenario_simulation: "true"
              use_foa: "false"
              perception/enable_traffic_light: "false"
