version: 2

artifacts:
  - name: planning
    build:
      type: custom
      runtime:
        type: standard1/arm64/large
      source:
        vcstool:
          repositories_files:
            - autoware.repos
          import_path: src
      base_container_image:
        from: ghcr.io/oguzkaganozt/autoware-openadk:planning-demo-before-ota-aarch64
      phases:
        - name: init
          exec: "true"
      output_container_image:
        from: init
        workdir: /autoware
  - name: scenario_simulator_v2
    build:
      type: custom
      runtime:
        type: standard1/arm64/large
      source:
        vcstool:
          repositories_files:
            - autoware.repos
          import_path: src
      base_container_image:
        from: ros:humble-ros-base-jammy
      phases:
        - name: install-middleware
          exec: ./.webauto-ci/scenario_simulator_v2/install-middleware/run.sh
          caches:
            - name: apt-lists
              mountpoint: /var/lib/apt/lists
            - name: apt-archives
              mountpoint: /var/cache/apt/archives
          build_result_reuse:
            key_files:
              - .webauto-ci/scenario_simulator_v2/install-middleware/**/*
        - name: colcon-build
          exec: ./.webauto-ci/scenario_simulator_v2/colcon-build/run.sh
          environment_variables:
            WORKDIR: /home/ubuntu/Desktop/scenario_simulator_ws
          caches:
            - name: apt-lists
              mountpoint: /var/lib/apt/lists
            - name: apt-archives
              mountpoint: /var/cache/apt/archives
      output_container_image:
        from: colcon-build
        workdir: /home/ubuntu/Desktop/scenario_simulator_ws

simulations:
  - name: planning_sim
    type: planning_sim_v2
    simulator:
      deployment:
        type: container
        artifact: scenario_simulator_v2
      runtime:
        type: standard1/arm64/medium
      parameters:
        launch_autoware: "false"
        autoware_launch_package: autoware_launch
        autoware_launch_file: planning_simulator.launch.xml
        architecture_type: awf/universe
        vehicle_model: sample_vehicle
        sensor_model: sample_sensor_kit
        initialize_duration: "45"
    components:
      - name: planning
        deployment:
          type: container
          artifact: planning
        runtime:
          type: standard1/arm64/medium
        application:
          roslaunch:
            package_name: autoware_launch
            file_name: planning_simulator.launch.xml
            arguments:
              architecture_type: awf/universe
              sensor_model: sample_sensor_kit
              vehicle_model: sample_vehicle
              map_path: ${map_path}
